binary_strings.out: binary_strings.o
	gcc -g -Wall -Werror -o binary_strings.out binary_strings.o

binary_strings.o: binary_strings.c
	gcc -g -Wall -Werror -c binary_strings.c

clean:
	rm -fr *.o *.out